- name: aknierim/AP
  subdirectory:
    - SoSe
    - WiSe
  pdfs:
    directory: Protokolle
- name: AReinold/Bachelor-FP
  pdfs:
    directory: Abtestate_PDF # TODO: werden noch nicht erkannt
- name: AReinold/Master-FP
  pdfs:
    directory: PDF-Dateien abtestiert
- name: Bastian125/AP-Praktikum
  pdfs:
    directory: Versuche
# TODO: Mehrere Unterordner, auch für PDFs
- name: BenediktSan/AnfaengerPraktikum2020
  subdirectory:
    # - Finale_Abgaben
    - Versuche Semester III
    - Versuche Semester IV
  pdfs:
    in_source_dir: true
- name: BenediktSan/FortgeschrittenenPraktikum2022
  subdirectory:
    - Versuche Semester VI
  pdfs:
    in_source_dir: true
- name: bixel/AP1213
  dirs_to_versuche:
    V501-2_E-B-Feld: 501 # in der Datei steht fälschlicherweise V406
  pdfs:
    in_source_dir: true
- name: bixel/FP14
# TODO: hat Altprotokolle in Unterordnern
- name: brkkbkc/FPSS18_5
- name: chrbeckm/anfaenger-praktikum
- name: chrbeckm/tudo-physik-fp
- name: Christopherkrause1/FortgeschrittenesPraktikum
- name: Christopherkrause1/Praktikum
- name: chris-topher6/Anfaenger-Praktikum
  dirs_to_versuche:
    V302: 302 # in der Datei steht fälschlicherweise V301
- name: dagbjoern/AP-Physik
  pdfs:
    in_source_dir: true
- name: dagbjoern/FP-Physik
- name: DaGutn/david-praktikum
  dirs_to_versuche:
    Comptoneffekt: 603
    Geiger-Mueller-Zaehlrohr: 703
    Röntgenemission und -absorption: 602
  subdirectory: Documents/Projects/david-praktikum
- name: DaGutn/FP_David_Lasse
  pdfs:
    in_source_dir: true # TODO: werden noch nicht erkannt
- name: DavidP181/FP
  pdfs:
    in_source_dir: true
- name: dlmsr/praktikum
- name: dormail/ap
- name: elliekayl/Protokolle
  pdfs:
    directory:
      - US
      - V01-46
      - V100-V354
      - V400-703
- name: FeGeyer/praktikum
  subdirectory:
    - 3_Semester
    - 4_Semester
    - BFP
    - MFP
  pdfs:
    directory:
      - 3_Semester/PDF Dateien
      - 4_Semester/PDF-Dateien
      - BFP/PDF Dateien
      - MFP/PDF-Dateien # TODO: Versuch-Nummern fehlen
- name: Fresoquark/Anfaengerpraktikum
- name: FSchierok/FP
- name: HelenaCarlArne/ProtokolleAP
- name: HelenaCarlArne/ProtokolleFP
- name: henne169/FP
  pdfs:
    in_source_dir: true
- name: henningpt/FP-Physik
- name: henningpt/Master_Praktikum
  dirs_to_versuche:
    v61_dag: 61
- name: Imigir/Physik-Praktikum
  dirs_to_versuche:
    23-Praktikum-V501-502: 501 # Doppelversuch
  parsing:
    contents: false # Die „…w.tex“ genannten Dateien stören die Erkennung sonst erheblich.
  pdfs:
    in_source_dir: true
- name: JaLuka98/AP_17-18
  dirs_to_versuche:
    latex-template: false
    V701_reichweite_von_alpha-Strahlung: 701 # in der Datei steht fälschlicherweise V704
- name: JaLuka98/FP_SS19
  dirs_to_versuche:
    latex-template: false
- name: JaLuka98/FP_WS19-20
- name: jana-banana/AP-2020
  subdirectory: we did that
  pdfs:
    in_source_dir: true
- name: jana-banana/FP-2022
- name: JaSale/AP
  dirs_to_versuche:
    V701: 701 # in der Datei steht fälschlicherweise 402
  pdfs:
    directory: PDF
- name: JaSale/FP
- name: JaSchl/AP1718
  pdfs:
    in_source_dir: true
# TODO: PDFs heißen „proto.pdf“
- name: JaSchl/FP1819
- name: Jean1995/Praktikum
  dirs_to_versuche:
    latex-template_V01: false
  pdfs:
    directory: Protokolle_Fertig
- name: Jean1995/PraktikumFP
- name: JLammering/Master-Praktikum
  pdfs:
    in_source_dir: true
- name: JLammering/Physikalisches-Praktikum
  dirs_to_versuche:
    "15 Röntgenemission -absorption ": 602 # in der Datei steht fälschlicherweise V605
  parsing:
    dirname: false
- name: joeyko2706/Anfaengerpraktikum-20-21
  pdfs:
    directory: Protokolle
- name: jpherdi/FP_20_21
- name: jpherdi/Praktikum
- name: JulianSch/FP-Pelle-Julian
  dirs_to_versuche:
    V14-Topografie: 14 # in der Datei steht fälschlicherweise V01
  pdfs:
    directory: Altprotokolle_nYR
- name: KarlSchiller/2018-SS-FP
  dirs_to_versuche:
    V00: false
- name: KarlSchiller/2018-WS-FP
  dirs_to_versuche:
    V00: false
- name: kasperyvonne/MasterFP
- name: katrinbls/FP
- name: KattiBrae/APWS201718
  dirs_to_versuche:
    "Protokollgerüst": false
  subdirectory:
    - AP1
    - AP2
- name: KattiBrae/FPWS201819
  subdirectory:
    - BA_FP_Protokolle
    - MA_FP
  dirs_to_versuche:
    abtestiert_HeNeLaser: 61
    abtestiert_Myonen: 1
    abtestiert_optisches_pumpen: 21
    abtestiert_Quanten: 23
    abtestiert_Zeeman-Effekt: 27
    fp_prüfung: false
    protokollgerüst: false
    rutherford_abtestat: 16
# NOTE: KevSed/Praktikum_FP ist scheinbar eine ältere Version des Repos
- name: KevSed/Praktikum
# TODO: PDFs unregelmäßig benannt
- name: komrozik/AP2019
  pdfs:
    in_source_dir: true
- name: komrozik/AP2020
  pdfs:
    in_source_dir: true
- name: komrozik/FP2021
  pdfs:
    in_source_dir: true
- name: komrozik/Master_FP
- name: larsfu/ap
- name: larsfu/fp
- name: lassestern/FP_Master
# TODO: Versuch-Nummern aus den Literaturangaben übernommen; PDFs unregelmäßig benannt
- name: lassestern/Lasse_Praktikum
  dirs_to_versuche:
    Compton_Effekt: 603
    Geiger: 703
    Roentgenabsorption: 602
    # Wiederholungsaufgaben: …
  pdfs:
    in_source_dir: true
# TODO: unvollständige Versuch-Nummern; PDFs unregelmäßig benannt
- name: lassestern/praktikum-david-lasse
  pdfs:
    in_source_dir: true
- name: lfighter/FortgeschrittenesPraktikum
# TODO: hat PDFs, aber keine Versuchsnummer im Dateipfad
- name: lfighter/Praktikum
# TODO: unvollständige Versuch-Nummern
- name: LiigaSoolane/Paktikum-mit-dem-Teufel
# keine Versuch-Nummern oder main.tex – suche stattdessen nach "\newcommand{\VNr}{…}"
- name: LuckyJosh/APPhysik
  dirs_to_versuche:
    "Alphastrahlung[X]": 701
    "Brueckenschaltungen[X]": 302
    "Dampfdruck[X]": 203
    "Dopplereffekt[X]": 104
    "Drehschwingungen[X]": 102
    "DulongPetit[X]": 201
    "Elektronen[X]": 501
    "Fourier[X]": 351
    "FranckHertz[X]": 601
    "Geigerzaehler[ ]": 703
    "Gekoppleteschwingkreise[X]": 355
    "Lockin[X]": 303
    "Millikan[ ]": 503
    "Neutronen[ ]": 702
    "PhotoeffektII[ ]": 500 # V500a
    "Photoeffekt[ ]": 500
    "Relaxation[X]": 353
    # "Solarzelle[ ]": Nachholversuch
    "Traegheit[X]": 101 # aus dem Inhalt erschlossen
    "Viskositaet[X]": 207 # aus dem Inhalt erschlossen
    "Waermepumpe[X]": 206
    "geomOptik[X]": 408
# suche nach "\newcommand{\ENo}{…}"
- name: LuckyJosh/PhysikFP2015
  dirs_to_versuche:
    01_TomographieGamma[X]: 14
    02_ModulationDemodulation[X]: 59
    03_OptischesPumpen[X]: 21
    04_Diodenlaser[X]: 60
    05_Operationsverstaerker[X]: 51
    05_Operationsvertaerker[ ]: false
    06_ZeemannEffekt[X]: 27
    1_HeNe_Laser[X]: 61
    2_Vakuumphysik[X]: 70
    3_Mikrowellen[X]: 53
    4_DebyeScherrer[X]: 41
    5_ElektronenSpinResonanz[X]: 28
  pdfs:
    in_source_dir: true
- name: lukas-bert/AP-1-Versuchsprotokolle
  dirs_to_versuche:
    "vXXX": false
- name: LukasNickel/praktikumsskripte
  pdfs:
    in_source_dir: true
- name: lwitthaus/Anfaengerpraktikum
- name: maaxxns/FP_Samuel_Max
- name: MagischeMiesmuschel/AnfaengerPraktikum
- name: MagischeMiesmuschel/FPMaster
  pdfs:
    directory: Protokolle
- name: Mampfzwerg/FP
  pdfs:
    in_source_dir: true
- name: Mampfzwerg/Praktikum
  pdfs:
    in_source_dir: true
- name: marcelkebe/AP2020_together
- name: marcelkebe/exp2PH
  dirs_to_versuche:
    Der Compton-Effekt-20200429: 603
  subdirectory:
    - .
    - compton
  pdfs:
    in_source_dir: true
- name: maxnoe/tudo_masterfp
- name: MaxSac/AP-Praktikum
  dirs_to_versuche:
    01-20.Oktober: 103
    02-27.Oktober: 104 # nur Notizen
    23-28.Juni: 701 # unvollständig
  parsing:
    dirname: false
  pdfs:
    in_source_dir: true
- name: MaxSac/FP-Praktikum
  parsing:
    dirname: false
- name: MariusHotte/MaFP_HuMa
  pdfs:
    in_source_dir: true
- name: miriamsimm/FP
- name: moritzbo/anfaenger_praktikum
- name: moritzbo/fortgeschrittenes_praktikum
- name: mwindau/FP
  pdfs:
    directory: FP_Bachelor
    in_source_dir: true
  subdirectory:
    - FP_Master
- name: mwindau/praktikum
  pdfs:
    in_source_dir: true
- name: nbiederbeck/masterpraktikum
  dirs_to_versuche:
    99-Pruefung: false
  parsing:
    dirname: false
- name: NicoJG/Anfaengerpraktikum
  pdfs:
    in_source_dir: true
- name: NicoJG/Fortgeschrittenenpraktikum
  pdfs:
    in_source_dir: true
# die PDFs sind auf GitHub Pages…
- name: NicoWeio/AP
  branch: gh-pages
  pdfs:
    in_source_dir: true
# die PDFs sind auf GitHub Pages…
- name: NicoWeio/FP
  branch: gh-pages
  pdfs:
    in_source_dir: true
# Fork von BenediktSan/AnfaengerPraktikum2020
# - name: NiklasD/AnfaengerPraktikum2020
- name: NilBre/4Physiker_Ap
  dirs_to_versuche:
    A10_Bearbeitung: false
- name: Ninilini/FP-Bachelor
- name: nsalewski/laboratory
  dirs_to_versuche:
    Vorlage Protokoll: false
  subdirectory:
    - .
    - FP
# einige Versuch-Nummern stehen nicht in separaten Makros
- name: pascalgutjahr/Praktikum-1
  dirs_to_versuche:
    DopplerSono: 903
    Elektronenemission: 504
    GeometOptik: 408
    Millikan: 503
- name: paul-stoerbrock/Praktikum
- name: phlipo95/AP-Praktikum
- name: phlipo95/FP-Praktikum
- name: Renameus/PhysikPraktikum1
  pdfs:
    in_source_dir: true
  subdirectory: Versuche
- name: Renameus/PhysikPraktikum2
  pdfs:
    in_source_dir: true
  subdirectory: Versuche
- name: rkallo/APWS1718
  dirs_to_versuche:
    "105": 105 # in der Datei steht fälschlicherweise V101
    "703": 703 # in der Datei steht fälschlicherweise V606
  pdfs:
    in_source_dir: true
- name: rkallo/FPWS1819
  pdfs:
    in_source_dir: true
- name: rleven/Praktikum2020
- name: rleven/richard_joell_Praktikum
- name: RnLe/AP1920-AJRM
  pdfs:
    directory: Einzelversuche/AJB
    in_source_dir: true
- name: Robubabu/FFS-Praktikum
  dirs_to_versuche:
    V401-Michelson-Interferometer: 401 # in der Datei steht fälschlicherweise 403
    V602-Röntgenemission_und-absorption: 602 # in der Datei steht fälschlicherweise 603
    Zettel1: false
  pdfs:
    directory: Versuchs_pdfs
- name: Robubabu/YR-Praktikum
# - name: SamGTex/FP # TODO: noch leer
- name: SamGTex/Physik_Praktikum_Samuel_Max
# TODO: PDFs in „BFP“ werden noch nicht erkannt
- name: SanjoR/FP-Jonas-Donata
  pdfs:
    directory: MFP/Fertige_Protokolle
  subdirectory:
    - BFP
    - MFP
- name: SHilgers/Praktikum2
- name: smjhnits/Praktikum_TU_D_16-17
  pdfs:
    directory: Anfängerpraktikum/Fertige Protokolle
    in_source_dir: true
  subdirectory:
    - Anfängerpraktikum/Protokolle
    - Fortgeschrittenenpraktikum/Protokolle
- name: smjolame/Fortgeschrittenenpraktikum
  dirs_to_versuche:
    template: false
- name: smjolame/Praktikum_1
  pdfs:
    in_source_dir: true
- name: smrakais/Master-Praktikum
  pdfs:
    in_source_dir: true
- name: stefangri/s_s_masterpraktikum
- name: stefangri/s_s_productions
  subdirectory: PHY341
- name: LarsKolk/Anfaengerpraktikum
  dirs_to_versuche:
    V303-Lock-In-Verstärker: 303 # in der Datei steht fälschlicherweise V351
  pdfs:
    in_source_dir: true
- name: Tahirbanane/AP
  pdfs:
    in_source_dir: true
- name: Tahirbanane/FP_2022
- name: TimBizeps/BachelorAP
  pdfs:
    in_source_dir: true
- name: TRose27/FP
- name: ttros/Praktikum
  subdirectory: Protokolle
- name: Vale112/FP_B_SS19
  dirs_to_versuche:
    V00: false
- name: vsulaiman/Praktikum
  subdirectory:
    - SS17
    - WS1617
  pdfs:
    directory: AP Protokolle
- name: woklop9/Anfaengerpraktikum
# keine vollständigen Protokolle
# - name: xxholzixx1/Anfaengerpraktikum
- name: YanickKi/AP_T_Y
