- name: aknierim/AP
- name: BenediktSan/AnfaengerPraktikum2020
- name: chrbeckm/anfaenger-praktikum
- name: chris-topher6/Anfaenger-Praktikum
- name: dagbjoern/AP-Physik
- name: dlmsr/praktikum
- name: dormail/ap
- name: Fresoquark/Anfaengerpraktikum
- name: HelenaCarlArne/ProtokolleAP
- name: Jean1995/Praktikum
- name: JLammering/Physikalisches-Praktikum
- name: komrozik/AP2019
- name: lassestern/praktikum-david-lasse
- name: LiigaSoolane/Paktikum
- name: LuckyJosh/APPhysik
- name: MagischeMiesmuschel/AnfaengerPraktikum
- name: Mampfzwerg/Praktikum
- name: moritzbo/anfaenger_praktikum
- name: mwindau/praktikum
- name: NicoJG/Anfaengerpraktikum
- name: NicoWeio/AP
- name: NiklasD/AnfaengerPraktikum2020
- name: nsalewski/laboratory
- name: pascalgutjahr/Praktikum-1
- name: paul-stoerbrock/Praktikum
- name: phlipo95/AP-Praktikum
- name: Renameus/PhysikPraktikum1
  subdirectory: Versuche
- name: rkallo/APWS1718
- name: rleven/richard_joell_Praktikum
- name: SamGTex/Physik_Praktikum_Samuel_Max
- name: SHilgers/Praktikum2
- name: smjhnits/Praktikum_TU_D_16-17
  subdirectory: Anfängerpraktikum/Protokolle
- name: smjolame/Praktikum_1
- name: stefangri/s_s_productions
- name: syhon/Anfaengerpraktikum
- name: Tahirbanane/AP
- name: vsulaiman/Praktikum
  subdirectory: AP Protokolle
- name: woklop9/Anfaengerpraktikum
- name: YanickKi/AP_T_Y
